w7d3/fff/jungle-rails/config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show] do
    resources :reviews, only: [:create, :destroy]
  end
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    put    :add_item
    delete :remove_item
  end

  resources :orders, only: [:create, :show]

  resources :users, only: [:create, :new]

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show]
  end

end

w7d3/fff/jungle-rails/app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category
  has_many :reviews

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true

  def average_rating
    average = 0

    if reviews.count > 0
      average = reviews.inject(0) { |sum, value| sum + value.rating.to_i } / reviews.count
    end

    average
  end

  def sold_out?
    quantity.to_i == 0
  end
end

w7d3/fff/jungle-rails/app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: ENV['ADMIN_NAME'], password: ENV['ADMIN_PWD']
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

w7d3/fff/jungle-rails/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
    @review = Review.new


  end

end

w7d3/fff/jungle-rails/app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
      <%= image_tag product.image.thumb, alt: product.name %>
      <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <%= link_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary', method: :put do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>

<% if product.sold_out? -%>
    <aside class="soldout">
      SOLD OUT
    </aside>

<% end -%>


  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
</article>

<aside class="quantity">
    <%= %>
  </aside>

w7d3/fff/jungle-rails/app/views/products/_review.html.erb
<li class="review-list__item">
  <header class="review-list__item__header">
    <span class="review-list__item--username"> <%= user.name %> </span>
    <span class="review-list__item--rating"> Rating: <%= review.rating %>/5 </span>
  </header>
  <div class="review-list__item--body">
    <span class="review-list__item--description"> <%= review.description %> </span>
  </div>
  <div class="review-list__item--footer">
    <span class="review-list__item--created-at"> Created At: <%= review.created_at %> </span>
  </div>

  <% if review.user == current_user %>
     <%= link_to fa_icon('trash'), [@product, @review], class: 'delete__button btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

w7d3/fff/jungle-rails/app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

w7d3/fff/jungle-rails/app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd><%= @product.price %></dd>
          <dt>Average Rating </dt>
          <dd><%= @product.average_rating %> </dd>
        </dl>
      </div>

      <div class="col-sm-8 review-container">
        <div class="review-input">
          <% if @user_reviewed %>
            <%= "You have already commented" %>
           <% else %>
            <%= form_for [@product, @review] do |f| %>
              <p> <%= f.label :rating %> </p>
              <p> <%= f.select :rating, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5]]  %> </p>
              <p> <%= f.label :description %> </p>
              <p> <%= f.text_area :description %> </p>
              <p class="submit__button"> <%= f.submit "Submit Review" %> </p>
              <% end %>
          <% end %>
        </div>
        <p class="comments__header">Comments: </p>
        <ul class="review-list">
          <% @product.reviews.reverse.each do |review| %>
            <% @review = review %>
            <% @user = review.user %>
            <%= render partial: "review", locals: {review: @review, user: @user } %>
          <% end %>
        </ul>
      </div>
    </div>

  </article>

</section>